In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [ ]:
tickers = ['NVDA', 'WMT','AAPL','AMZN','MSFT']

In [3]:
prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_55260/1012360723.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
[*********************100%***********************]  5 of 5 completed

Ticker            AAPL        AMZN        MSFT        NVDA         WMT
Date
2024-01-02  183.404007  149.929993  363.117920   48.082535   51.641460
2024-01-03  182.030746  148.470001  362.853577   47.484592   51.644699
2024-01-04  179.718918  144.570007  360.249146   47.912842   51.145428
2024-01-05  178.997711  145.240005  360.063141   49.009888   50.805035
2024-01-08  183.324966  149.100006  366.858093   52.160286   51.304291
...                ...         ...         ...         ...         ...
2026-08-19  316.829987  265.839996  483.399994  217.559998  114.027023
2026-08-20  311.299988  260.109985  481.149994  216.850006  103.591995
2026-08-21  309.350006  258.630005  483.239990  214.720001  103.699997
2026-08-24  310.339996  262.070007  487.309998  208.479996  106.489998
2026-08-25  309.899994  261.059998  491.709991  213.050003  105.379997

[664 rows x 5 columns]

In [4]:
# Calcular los rendimientos
rets = (prices/prices.shift() - 1).dropna() # Eliminar las filas con valores NaN
rets

Ticker          AAPL      AMZN      MSFT      NVDA       WMT
Date
2024-01-03 -0.007488 -0.009738 -0.000728 -0.012436  0.000063
2024-01-04 -0.012700 -0.026268 -0.007178  0.009019 -0.009667
2024-01-05 -0.004013  0.004634 -0.000516  0.022897 -0.006655
2024-01-08  0.024175  0.026577  0.018872  0.064281  0.009827
2024-01-09 -0.002263  0.015225  0.002936  0.016975  0.006698
...              ...       ...       ...       ...       ...
2026-08-19  0.021933  0.024629  0.005564 -0.009921 -0.007812
2026-08-20 -0.017454 -0.021554 -0.004655 -0.003263 -0.091514
2026-08-21 -0.006264 -0.005690  0.004344 -0.009822  0.001043
2026-08-24  0.003200  0.013301  0.008422 -0.029061  0.026905
2026-08-25 -0.001418 -0.003854  0.009029  0.021921 -0.010424

[663 rows x 5 columns]

In [5]:
#Rendimiento esperado de cada activo
mu=rets.mean()

In [6]:
#Rendimiento Portafolio
w=np.array([0.2, 0.2, 0.2, 0.2, 0.2])  # Pesos del portafolio (20% cada activo)
R_port=sum(w*mu)
R_port*100*252

32.65586970088332

In [8]:
#Riesgo de un portafolio
cov=rets.cov()
vol_port=np.sqrt(w.T @ cov @ w)
vol_port*100*np.sqrt(252)

np.float64(21.474652836724697)

In [ ]:
cov
#no podemos interpretar estos 0 porque la magnitud 
# va a tomar el valor abosluto y los va a sumar

Ticker      AAPL      AMZN      MSFT      NVDA       WMT
Ticker
AAPL    0.000305  0.000130  0.000099  0.000159  0.000062
AMZN    0.000130  0.000423  0.000185  0.000276  0.000046
MSFT    0.000099  0.000185  0.000287  0.000219  0.000019
NVDA    0.000159  0.000276  0.000219  0.000922  0.000014
WMT     0.000062  0.000046  0.000019  0.000014  0.000218

In [10]:
rets.corr()

Ticker      AAPL      AMZN      MSFT      NVDA       WMT
Ticker
AAPL    1.000000  0.361332  0.334405  0.299800  0.241137
AMZN    0.361332  1.000000  0.532321  0.442677  0.150536
MSFT    0.334405  0.532321  1.000000  0.426770  0.076781
NVDA    0.299800  0.442677  0.426770  1.000000  0.032101
WMT     0.241137  0.150536  0.076781  0.032101  1.000000

In [ ]:
#Correlación es baja cuando esta entre-.25 y +.25
#Cuadrada es decir de nxn activos
#Y es una matriz simétrica,