# **Actividad en Equipos - Calculo de Black Scholes**
## **Simulación de Procesos Financieros**

---

**Autores:** Francisco Uriel Ledezma Chávez  
**Carrera:** Ingeniería Financiera  
**Institución:** ITESO — Universidad Jesuita de Guadalajara  
**Semestre:** 5° — Simulación de Procesos Financieros  
**Fecha de realización:** 23 de agosto de 2026

---

En este notebook se simulan riesgo y rendimientos de un activo, con el propósito de observar cómo puede fluctuar su precio (10,000) veces al 01 de Julio del presente.

## Índice de contenidos

1. Sección 1 — Ingesta de Datos a Modelar
2. Sección 2 — Train-Test Split
3. Sección 3 — Observaciones y Análisis
4. Sección 4 — Calculo Objetivo

## Importación de bibliotecas

In [189]:
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [190]:
Prices = yf.download('KO', start='2026-01-01', end='2026-08-31')['Close']
Prices.dropna(inplace=True)
Prices

[*********************100%***********************]  1 of 1 completed

Ticker             KO
Date
2026-01-02  68.207611
2026-01-05  67.043182
2026-01-06  66.944496
2026-01-07  66.648468
2026-01-08  68.454315
...               ...
2026-08-21  91.099998
2026-08-24  91.989998
2026-08-25  91.639999
2026-08-26  90.080002
2026-08-27  89.059998

[164 rows x 1 columns]

---

## Análisis de la Ingesta

In [191]:
Rendimientos = (Prices / Prices.shift(1) - 1).dropna()
Rendimientos

Ticker            KO
Date
2026-01-05 -0.017072
2026-01-06 -0.001472
2026-01-07 -0.004422
2026-01-08  0.027095
2026-01-09  0.016434
...              ...
2026-08-21  0.006630
2026-08-24  0.009769
2026-08-25 -0.003805
2026-08-26 -0.017023
2026-08-27 -0.011323

[163 rows x 1 columns]

## Train-Test Split

In [192]:
Train = Rendimientos[Rendimientos.index < "2026-05-01"]
Test = Rendimientos[(Rendimientos.index >= "2026-05-01") & (Rendimientos.index < "2026-07-01")]

## Análisis con Train

In [193]:
Mu = Train.mean()
Sigma = Train.std()

print(Mu, Sigma)

Ticker
KO    0.001763
dtype: float64 Ticker
KO    0.011509
dtype: float64

In [194]:
S_0 = Prices.loc[:'2026-04-30'].iloc[-1]
r = Mu
sigma = Sigma
T = len(Prices.loc[:'2026-04-30']) - 1
K = Prices.loc['2026-07-01']

In [195]:
S_0

Ticker
KO    78.254768
Name: 2026-04-30 00:00:00, dtype: float64

In [196]:
len(Test)

41

In [197]:
len(Train)

81

In [198]:
resultados = []

for i in range(10000):
    S_t = S_0 * np.exp((r - 0.5 * sigma ** 2) * T + sigma * np.sqrt(T) * np.random.normal(0, 1))
    resultados.append(S_t)

len(resultados)

10000

In [199]:
resultados

[Ticker
 KO    85.294803
 dtype: float64,
 Ticker
 KO    103.737651
 dtype: float64,
 Ticker
 KO    98.374128
 dtype: float64,
 Ticker
 KO    89.534119
 dtype: float64,
 Ticker
 KO    89.603425
 dtype: float64,
 Ticker
 KO    96.841298
 dtype: float64,
 Ticker
 KO    78.142987
 dtype: float64,
 Ticker
 KO    100.921799
 dtype: float64,
 Ticker
 KO    101.547412
 dtype: float64,
 Ticker
 KO    76.829756
 dtype: float64,
 Ticker
 KO    66.066663
 dtype: float64,
 Ticker
 KO    89.458098
 dtype: float64,
 Ticker
 KO    83.866344
 dtype: float64,
 Ticker
 KO    84.693646
 dtype: float64,
 Ticker
 KO    77.58259
 dtype: float64,
 Ticker
 KO    92.563009
 dtype: float64,
 Ticker
 KO    82.587174
 dtype: float64,
 Ticker
 KO    109.103026
 dtype: float64,
 Ticker
 KO    89.686948
 dtype: float64,
 Ticker
 KO    77.943373
 dtype: float64,
 Ticker
 KO    81.643634
 dtype: float64,
 Ticker
 KO    83.628003
 dtype: float64,
 Ticker
 KO    95.958087
 dtype: float64,
 Ticker
 KO    87.480052
 dtype: float64,
 Ticker
 KO    82.394376
 dtype: float64,
 Ticker
 KO    83.72215
 dtype: float64,
 Ticker
 KO    110.04247
 dtype: float64,
 Ticker
 KO    90.759907
 dtype: float64,
 Ticker
 KO    92.759376
 dtype: float64,
 Ticker
 KO    105.414916
 dtype: float64,
 Ticker
 KO    96.550953
 dtype: float64,
 Ticker
 KO    83.254101
 dtype: float64,
 Ticker
 KO    84.597346
 dtype: float64,
 Ticker
 KO    82.055182
 dtype: float64,
 Ticker
 KO    77.473086
 dtype: float64,
 Ticker
 KO    82.839604
 dtype: float64,
 Ticker
 KO    99.70922
 dtype: float64,
 Ticker
 KO    89.278261
 dtype: float64,
 Ticker
 KO    91.285591
 dtype: float64,
 Ticker
 KO    92.141561
 dtype: float64,
 Ticker
 KO    85.482967
 dtype: float64,
 Ticker
 KO    93.645268
 dtype: float64,
 Ticker
 KO    90.945906
 dtype: float64,
 Ticker
 KO    83.169742
 dtype: float64,
 Ticker
 KO    96.04766
 dtype: float64,
 Ticker
 KO    95.145512
 dtype: float64,
 Ticker
 KO    77.008189
 dtype: float64,
 Ticker
 KO    89.755112
 dtype: float64,
 Ticker
 KO    91.434976
 dtype: float64,
 Ticker
 KO    82.219406
 dtype: float64,
 Ticker
 KO    91.840071
 dtype: float64,
 Ticker
 KO    85.814016
 dtype: float64,
 Ticker
 KO    93.251932
 dtype: float64,
 Ticker
 KO    85.341717
 dtype: float64,
 Ticker
 KO    75.065544
 dtype: float64,
 Ticker
 KO    80.437017
 dtype: float64,
 Ticker
 KO    107.190519
 dtype: float64,
 Ticker
 KO    79.227768
 dtype: float64,
 Ticker
 KO    100.566342
 dtype: float64,
 Ticker
 KO    85.918922
 dtype: float64,
 Ticker
 KO    91.913772
 dtype: float64,
 Ticker
 KO    96.099281
 dtype: float64,
 Ticker
 KO    91.796158
 dtype: float64,
 Ticker
 KO    87.387435
 dtype: float64,
 Ticker
 KO    93.616132
 dtype: float64,
 Ticker
 KO    88.126585
 dtype: float64,
 Ticker
 KO    89.094654
 dtype: float64,
 Ticker
 KO    69.223619
 dtype: float64,
 Ticker
 KO    96.038044
 dtype: float64,
 Ticker
 KO    92.585305
 dtype: float64,
 Ticker
 KO    80.786156
 dtype: float64,
 Ticker
 KO    104.334854
 dtype: float64,
 Ticker
 KO    92.305229
 dtype: float64,
 Ticker
 KO    103.694518
 dtype: float64,
 Ticker
 KO    100.851583
 dtype: float64,
 Ticker
 KO    74.06266
 dtype: float64,
 Ticker
 KO    105.904996
 dtype: float64,
 Ticker
 KO    90.19451
 dtype: float64,
 Ticker
 KO    86.694551
 dtype: float64,
 Ticker
 KO    108.669269
 dtype: float64,
 Ticker
 KO    85.20064
 dtype: float64,
 Ticker
 KO    80.788593
 dtype: float64,
 Ticker
 KO    86.616079
 dtype: float64,
 Ticker
 KO    85.390848
 dtype: float64,
 Ticker
 KO    112.922648
 dtype: float64,
 Ticker
 KO    96.952741
 dtype: float64,
 Ticker
 KO    84.447979
 dtype: float64,
 Ticker
 KO    85.3363
 dtype: float64,
 Ticker
 KO    92.387681
 dtype: float64,
 Ticker
 KO    96.546423
 dtype: float64,
 Ticker
 KO    102.777849
 dtype: float64,
 Ticker
 KO    107.5249
 dtype: float64,
 Ticker
 KO    105.503611
 dtype: float64,
 Ticker
 KO    88.279545
 dtype: float64,
 Ticker
 KO    97.628657
 dtype: float64,
 Ticker
 KO    84.542119
 dtype: float64,
 Ticker
 KO    101.12756
 dtype: float64,
 Ticker
 KO    97.65639
 dtype: float64,
 Ticker
 KO    92.611153
 dtype: float64,
 Ticker
 KO    77.157176
 dtype: float64,
 Ticker
 KO    88.607802
 dtype: float64,
 Ticker
 KO    93.164888
 dtype: float64,
 Ticker
 KO    110.84728
 dtype: float64,
 Ticker
 KO    77.250161
 dtype: float64,
 Ticker
 KO    92.178171
 dtype: float64,
 Ticker
 KO    102.427355
 dtype: float64,
 Ticker
 KO    97.460466
 dtype: float64,
 Ticker
 KO    72.294509
 dtype: float64,
 Ticker
 KO    96.418952
 dtype: float64,
 Ticker
 KO    99.440037
 dtype: float64,
 Ticker
 KO    91.14616
 dtype: float64,
 Ticker
 KO    84.590121
 dtype: float64,
 Ticker
 KO    82.742131
 dtype: float64,
 Ticker
 KO    101.256896
 dtype: float64,
 Ticker
 KO    87.737303
 dtype: float64,
 Ticker
 KO    81.458777
 dtype: float64,
 Ticker
 KO    97.248094
 dtype: float64,
 Ticker
 KO    91.384363
 dtype: float64,
 Ticker
 KO    97.06191
 dtype: float64,
 Ticker
 KO    94.253371
 dtype: float64,
 Ticker
 KO    87.801069
 dtype: float64,
 Ticker
 KO    91.826495
 dtype: float64,
 Ticker
 KO    82.14131
 dtype: float64,
 Ticker
 KO    81.790344
 dtype: float64,
 Ticker
 KO    94.408388
 dtype: float64,
 Ticker
 KO    87.501093
 dtype: float64,
 Ticker
 KO    81.734579
 dtype: float64,
 Ticker
 KO    91.145976
 dtype: float64,
 Ticker
 KO    84.866109
 dtype: float64,
 Ticker
 KO    89.85767
 dtype: float64,
 Ticker
 KO    92.692457
 dtype: float64,
 Ticker
 KO    95.566912
 dtype: float64,
 Ticker
 KO    74.876075
 dtype: float64,
 Ticker
 KO    75.199976
 dtype: float64,
 Ticker
 KO    71.63383
 dtype: float64,
 Ticker
 KO    72.255922
 dtype: float64,
 Ticker
 KO    80.87859
 dtype: float64,
 Ticker
 KO    102.042744
 dtype: float64,
 Ticker
 KO    82.60305
 dtype: float64,
 Ticker
 KO    100.069994
 dtype: float64,
 Ticker
 KO    92.793447
 dtype: float64,
 Ticker
 KO    100.961488
 dtype: float64,
 Ticker
 KO    96.413342
 dtype: float64,
 Ticker
 KO    93.023773
 dtype: float64,
 Ticker
 KO    81.322329
 dtype: float64,
 Ticker
 KO    83.925812
 dtype: float64,
 Ticker
 KO    88.91304
 dtype: float64,
 Ticker
 KO    81.86553
 dtype: float64,
 Ticker
 KO    102.140513
 dtype: float64,
 Ticker
 KO    98.496478
 dtype: float64,
 Ticker
 KO    89.848788
 dtype: float64,
 Ticker
 KO    105.4413
 dtype: float64,
 Ticker
 KO    102.683968
 dtype: float64,
 Ticker
 KO    100.116709
 dtype: float64,
 Ticker
 KO    91.519873
 dtype: float64,
 Ticker
 KO    104.521073
 dtype: float64,
 Ticker
 KO    95.198459
 dtype: float64,
 Ticker
 KO    90.20575
 dtype: float64,
 Ticker
 KO    89.020447
 dtype: float64,
 Ticker
 KO    76.36719
 dtype: float64,
 Ticker
 KO    84.363858
 dtype: float64,
 Ticker
 KO    96.08602
 dtype: float64,
 Ticker
 KO    93.086275
 dtype: float64,
 Ticker
 KO    89.914155
 dtype: float64,
 Ticker
 KO    95.149588
 dtype: float64,
 Ticker
 KO    82.780352
 dtype: float64,
 Ticker
 KO    97.309193
 dtype: float64,
 Ticker
 KO    95.404071
 dtype: float64,
 Ticker
 KO    91.284707
 dtype: float64,
 Ticker
 KO    96.199729
 dtype: float64,
 Ticker
 KO    89.880626
 dtype: float64,
 Ticker
 KO    85.351463
 dtype: float64,
 Ticker
 KO    102.339067
 dtype: float64,
 Ticker
 KO    80.939098
 dtype: float64,
 Ticker
 KO    80.208575
 dtype: float64,
 Ticker
 KO    87.37387
 dtype: float64,
 Ticker
 KO    96.203634
 dtype: float64,
 Ticker
 KO    89.638839
 dtype: float64,
 Ticker
 KO    84.420592
 dtype: float64,
 Ticker
 KO    79.81098
 dtype: float64,
 Ticker
 KO    84.031557
 dtype: float64,
 Ticker
 KO    95.401123
 dtype: float64,
 Ticker
 KO    93.411665
 dtype: float64,
 Ticker
 KO    90.289392
 dtype: float64,
 Ticker
 KO    74.249636
 dtype: float64,
 Ticker
 KO    89.760189
 dtype: float64,
 Ticker
 KO    96.215428
 dtype: float64,
 Ticker
 KO    83.563978
 dtype: float64,
 Ticker
 KO    85.374206
 dtype: float64,
 Ticker
 KO    99.231078
 dtype: float64,
 Ticker
 KO    91.919281
 dtype: float64,
 Ticker
 KO    96.867396
 dtype: float64,
 Ticker
 KO    106.307066
 dtype: float64,
 Ticker
 KO    88.38321
 dtype: float64,
 Ticker
 KO    75.710576
 dtype: float64,
 Ticker
 KO    102.342212
 dtype: float64,
 Ticker
 KO    81.030071
 dtype: float64,
 Ticker
 KO    81.358182
 dtype: float64,
 Ticker
 KO    86.122648
 dtype: float64,
 Ticker
 KO    93.522824
 dtype: float64,
 Ticker
 KO    86.723453
 dtype: float64,
 Ticker
 KO    86.903651
 dtype: float64,
 Ticker
 KO    103.402699
 dtype: float64,
 Ticker
 KO    87.349477
 dtype: float64,
 Ticker
 KO    85.293944
 dtype: float64,
 Ticker
 KO    96.972907
 dtype: float64,
 Ticker
 KO    91.88791
 dtype: float64,
 Ticker
 KO    97.652619
 dtype: float64,
 Ticker
 KO    91.995589
 dtype: float64,
 Ticker
 KO    96.376277
 dtype: float64,
 Ticker
 KO    96.493585
 dtype: float64,
 Ticker
 KO    96.399024
 dtype: float64,
 Ticker
 KO    84.390484
 dtype: float64,
 Ticker
 KO    98.533327
 dtype: float64,
 Ticker
 KO    79.528023
 dtype: float64,
 Ticker
 KO    82.643532
 dtype: float64,
 Ticker
 KO    86.779505
 dtype: float64,
 Ticker
 KO    100.025326
 dtype: float64,
 Ticker
 KO    98.502636
 dtype: float64,
 Ticker
 KO    97.676857
 dtype: float64,
 Ticker
 KO    98.173399
 dtype: float64,
 Ticker
 KO    87.05063
 dtype: float64,
 Ticker
 KO    114.878764
 dtype: float64,
 Ticker
 KO    80.425689
 dtype: float64,
 Ticker
 KO    84.256076
 dtype: float64,
 Ticker
 KO    100.692333
 dtype: float64,
 Ticker
 KO    85.824142
 dtype: float64,
 Ticker
 KO    92.697289
 dtype: float64,
 Ticker
 KO    93.027029
 dtype: float64,
 Ticker
 KO    116.980791
 dtype: float64,
 Ticker
 KO    73.422267
 dtype: float64,
 Ticker
 KO    96.937287
 dtype: float64,
 Ticker
 KO    75.971235
 dtype: float64,
 Ticker
 KO    78.669639
 dtype: float64,
 Ticker
 KO    90.80882
 dtype: float64,
 Ticker
 KO    96.330884
 dtype: float64,
 Ticker
 KO    80.82367
 dtype: float64,
 Ticker
 KO    83.624841
 dtype: float64,
 Ticker
 KO    79.565786
 dtype: float64,
 Ticker
 KO    90.442894
 dtype: float64,
 Ticker
 KO    91.780817
 dtype: float64,
 Ticker
 KO    85.325216
 dtype: float64,
 Ticker
 KO    82.587619
 dtype: float64,
 Ticker
 KO    76.444206
 dtype: float64,
 Ticker
 KO    106.880534
 dtype: float64,
 Ticker
 KO    92.604631
 dtype: float64,
 Ticker
 KO    86.730229
 dtype: float64,
 Ticker
 KO    110.983232
 dtype: float64,
 Ticker
 KO    102.056992
 dtype: float64,
 Ticker
 KO    76.340798
 dtype: float64,
 Ticker
 KO    78.588412
 dtype: float64,
 Ticker
 KO    77.600094
 dtype: float64,
 Ticker
 KO    95.443385
 dtype: float64,
 Ticker
 KO    117.213703
 dtype: float64,
 Ticker
 KO    84.989214
 dtype: float64,
 Ticker
 KO    98.512257
 dtype: float64,
 Ticker
 KO    95.424614
 dtype: float64,
 Ticker
 KO    88.69341
 dtype: float64,
 Ticker
 KO    85.700644
 dtype: float64,
 Ticker
 KO    82.593301
 dtype: float64,
 Ticker
 KO    89.347999
 dtype: float64,
 Ticker
 KO    91.313593
 dtype: float64,
 Ticker
 KO    94.380529
 dtype: float64,
 Ticker
 KO    66.317979
 dtype: float64,
 Ticker
 KO    96.590456
 dtype: float64,
 Ticker
 KO    93.741796
 dtype: float64,
 Ticker
 KO    84.157005
 dtype: float64,
 Ticker
 KO    104.611508
 dtype: float64,
 Ticker
 KO    90.928018
 dtype: float64,
 Ticker
 KO    91.291505
 dtype: float64,
 Ticker
 KO    93.159269
 dtype: float64,
 Ticker
 KO    73.948488
 dtype: float64,
 Ticker
 KO    78.953277
 dtype: float64,
 Ticker
 KO    90.057605
 dtype: float64,
 Ticker
 KO    86.322356
 dtype: float64,
 Ticker
 KO    88.09301
 dtype: float64,
 Ticker
 KO    72.497307
 dtype: float64,
 Ticker
 KO    97.637175
 dtype: float64,
 Ticker
 KO    87.025279
 dtype: float64,
 Ticker
 KO    84.324692
 dtype: float64,
 Ticker
 KO    84.537922
 dtype: float64,
 Ticker
 KO    87.803344
 dtype: float64,
 Ticker
 KO    101.577811
 dtype: float64,
 Ticker
 KO    93.655091
 dtype: float64,
 Ticker
 KO    88.069745
 dtype: float64,
 Ticker
 KO    82.059631
 dtype: float64,
 Ticker
 KO    86.043295
 dtype: float64,
 Ticker
 KO    92.409878
 dtype: float64,
 Ticker
 KO    87.927718
 dtype: float64,
 Ticker
 KO    86.83705
 dtype: float64,
 Ticker
 KO    78.679933
 dtype: float64,
 Ticker
 KO    72.978129
 dtype: float64,
 Ticker
 KO    80.631603
 dtype: float64,
 Ticker
 KO    86.989597
 dtype: float64,
 Ticker
 KO    86.298736
 dtype: float64,
 Ticker
 KO    91.116645
 dtype: float64,
 Ticker
 KO    82.951437
 dtype: float64,
 Ticker
 KO    84.729482
 dtype: float64,
 Ticker
 KO    78.021139
 dtype: float64,
 Ticker
 KO    95.601833
 dtype: float64,
 Ticker
 KO    82.284968
 dtype: float64,
 Ticker
 KO    87.304122
 dtype: float64,
 Ticker
 KO    90.12635
 dtype: float64,
 Ticker
 KO    78.169078
 dtype: float64,
 Ticker
 KO    79.432452
 dtype: float64,
 Ticker
 KO    95.309867
 dtype: float64,
 Ticker
 KO    89.624495
 dtype: float64,
 Ticker
 KO    95.031212
 dtype: float64,
 Ticker
 KO    86.39617
 dtype: float64,
 Ticker
 KO    107.485122
 dtype: float64,
 Ticker
 KO    69.840052
 dtype: float64,
 Ticker
 KO    76.692179
 dtype: float64,
 Ticker
 KO    95.546514
 dtype: float64,
 Ticker
 KO    99.414769
 dtype: float64,
 Ticker
 KO    70.507993
 dtype: float64,
 Ticker
 KO    81.531792
 dtype: float64,
 Ticker
 KO    85.115058
 dtype: float64,
 Ticker
 KO    93.392125
 dtype: float64,
 Ticker
 KO    87.337956
 dtype: float64,
 Ticker
 KO    83.993204
 dtype: float64,
 Ticker
 KO    93.666954
 dtype: float64,
 Ticker
 KO    99.006521
 dtype: float64,
 Ticker
 KO    67.121223
 dtype: float64,
 Ticker
 KO    87.927145
 dtype: float64,
 Ticker
 KO    79.391805
 dtype: float64,
 Ticker
 KO    93.406225
 dtype: float64,
 Ticker
 KO    77.19017
 dtype: float64,
 Ticker
 KO    89.212284
 dtype: float64,
 Ticker
 KO    107.743779
 dtype: float64,
 Ticker
 KO    90.595948
 dtype: float64,
 Ticker
 KO    93.028615
 dtype: float64,
 Ticker
 KO    79.381924
 dtype: float64,
 Ticker
 KO    99.151238
 dtype: float64,
 Ticker
 KO    98.585697
 dtype: float64,
 Ticker
 KO    82.452384
 dtype: float64,
 Ticker
 KO    81.154412
 dtype: float64,
 Ticker
 KO    105.454486
 dtype: float64,
 Ticker
 KO    101.517356
 dtype: float64,
 Ticker
 KO    85.537278
 dtype: float64,
 Ticker
 KO    93.571595
 dtype: float64,
 Ticker
 KO    97.857019
 dtype: float64,
 Ticker
 KO    77.762903
 dtype: float64,
 Ticker
 KO    88.552007
 dtype: float64,
 Ticker
 KO    73.758499
 dtype: float64,
 Ticker
 KO    87.142924
 dtype: float64,
 Ticker
 KO    96.894678
 dtype: float64,
 Ticker
 KO    84.160136
 dtype: float64,
 Ticker
 KO    82.890574
 dtype: float64,
 Ticker
 KO    86.05672
 dtype: float64,
 Ticker
 KO    89.022495
 dtype: float64,
 Ticker
 KO    90.075385
 dtype: float64,
 Ticker
 KO    91.654655
 dtype: float64,
 Ticker
 KO    100.231101
 dtype: float64,
 Ticker
 KO    79.869711
 dtype: float64,
 Ticker
 KO    91.364058
 dtype: float64,
 Ticker
 KO    92.469633
 dtype: float64,
 Ticker
 KO    95.07303
 dtype: float64,
 Ticker
 KO    95.919709
 dtype: float64,
 Ticker
 KO    96.438338
 dtype: float64,
 Ticker
 KO    87.051901
 dtype: float64,
 Ticker
 KO    84.159848
 dtype: float64,
 Ticker
 KO    82.817837
 dtype: float64,
 Ticker
 KO    100.56861
 dtype: float64,
 Ticker
 KO    77.361058
 dtype: float64,
 Ticker
 KO    70.552709
 dtype: float64,
 Ticker
 KO    89.638605
 dtype: float64,
 Ticker
 KO    92.61612
 dtype: float64,
 Ticker
 KO    82.653455
 dtype: float64,
 Ticker
 KO    90.579057
 dtype: float64,
 Ticker
 KO    81.474928
 dtype: float64,
 Ticker
 KO    77.146613
 dtype: float64,
 Ticker
 KO    75.816027
 dtype: float64,
 Ticker
 KO    94.786154
 dtype: float64,
 Ticker
 KO    86.213867
 dtype: float64,
 Ticker
 KO    88.53906
 dtype: float64,
 Ticker
 KO    88.222033
 dtype: float64,
 Ticker
 KO    90.793327
 dtype: float64,
 Ticker
 KO    91.080051
 dtype: float64,
 Ticker
 KO    77.509361
 dtype: float64,
 Ticker
 KO    88.161623
 dtype: float64,
 Ticker
 KO    95.596423
 dtype: float64,
 Ticker
 KO    87.104669
 dtype: float64,
 Ticker
 KO    98.21776
 dtype: float64,
 Ticker
 KO    106.09388
 dtype: float64,
 Ticker
 KO    96.299033
 dtype: float64,
 Ticker
 KO    121.935548
 dtype: float64,
 Ticker
 KO    83.257772
 dtype: float64,
 Ticker
 KO    95.01174
 dtype: float64,
 Ticker
 KO    81.244109
 dtype: float64,
 Ticker
 KO    96.873444
 dtype: float64,
 Ticker
 KO    91.656609
 dtype: float64,
 Ticker
 KO    86.937372
 dtype: float64,
 Ticker
 KO    62.319595
 dtype: float64,
 Ticker
 KO    87.154329
 dtype: float64,
 Ticker
 KO    91.329341
 dtype: float64,
 Ticker
 KO    80.109922
 dtype: float64,
 Ticker
 KO    81.704336
 dtype: float64,
 Ticker
 KO    80.720995
 dtype: float64,
 Ticker
 KO    94.413647
 dtype: float64,
 Ticker
 KO    80.306694
 dtype: float64,
 Ticker
 KO    108.128994
 dtype: float64,
 Ticker
 KO    93.366811
 dtype: float64,
 Ticker
 KO    75.810311
 dtype: float64,
 Ticker
 KO    83.481309
 dtype: float64,
 Ticker
 KO    79.199706
 dtype: float64,
 Ticker
 KO    99.485608
 dtype: float64,
 Ticker
 KO    92.158058
 dtype: float64,
 Ticker
 KO    76.175769
 dtype: float64,
 Ticker
 KO    100.905195
 dtype: float64,
 Ticker
 KO    80.015269
 dtype: float64,
 Ticker
 KO    106.842088
 dtype: float64,
 Ticker
 KO    106.133394
 dtype: float64,
 Ticker
 KO    79.828738
 dtype: float64,
 Ticker
 KO    85.223688
 dtype: float64,
 Ticker
 KO    97.385884
 dtype: float64,
 Ticker
 KO    94.163045
 dtype: float64,
 Ticker
 KO    80.201733
 dtype: float64,
 Ticker
 KO    92.38236
 dtype: float64,
 Ticker
 KO    99.318049
 dtype: float64,
 Ticker
 KO    109.804807
 dtype: float64,
 Ticker
 KO    93.794592
 dtype: float64,
 Ticker
 KO    93.01546
 dtype: float64,
 Ticker
 KO    88.340314
 dtype: float64,
 Ticker
 KO    87.865429
 dtype: float64,
 Ticker
 KO    97.235752
 dtype: float64,
 Ticker
 KO    87.239282
 dtype: float64,
 Ticker
 KO    81.611422
 dtype: float64,
 Ticker
 KO    78.669651
 dtype: float64,
 Ticker
 KO    95.485061
 dtype: float64,
 Ticker
 KO    76.136671
 dtype: float64,
 Ticker
 KO    86.632409
 dtype: float64,
 Ticker
 KO    85.749248
 dtype: float64,
 Ticker
 KO    82.96637
 dtype: float64,
 Ticker
 KO    83.983401
 dtype: float64,
 Ticker
 KO    81.088828
 dtype: float64,
 Ticker
 KO    87.873112
 dtype: float64,
 Ticker
 KO    92.885242
 dtype: float64,
 Ticker
 KO    81.453241
 dtype: float64,
 Ticker
 KO    85.317901
 dtype: float64,
 Ticker
 KO    88.208802
 dtype: float64,
 Ticker
 KO    82.593819
 dtype: float64,
 Ticker
 KO    89.349529
 dtype: float64,
 Ticker
 KO    95.967395
 dtype: float64,
 Ticker
 KO    85.897352
 dtype: float64,
 Ticker
 KO    110.237903
 dtype: float64,
 Ticker
 KO    97.576399
 dtype: float64,
 Ticker
 KO    96.330519
 dtype: float64,
 Ticker
 KO    89.467282
 dtype: float64,
 Ticker
 KO    105.706745
 dtype: float64,
 Ticker
 KO    76.699227
 dtype: float64,
 Ticker
 KO    75.649412
 dtype: float64,
 Ticker
 KO    78.019156
 dtype: float64,
 Ticker
 KO    81.956737
 dtype: float64,
 Ticker
 KO    79.31452
 dtype: float64,
 Ticker
 KO    82.826761
 dtype: float64,
 Ticker
 KO    83.457052
 dtype: float64,
 Ticker
 KO    86.202118
 dtype: float64,
 Ticker
 KO    96.017808
 dtype: float64,
 Ticker
 KO    66.251183
 dtype: float64,
 Ticker
 KO    85.806587
 dtype: float64,
 Ticker
 KO    103.426351
 dtype: float64,
 Ticker
 KO    93.252564
 dtype: float64,
 Ticker
 KO    70.459399
 dtype: float64,
 Ticker
 KO    107.672763
 dtype: float64,
 Ticker
 KO    105.125486
 dtype: float64,
 Ticker
 KO    92.232822
 dtype: float64,
 Ticker
 KO    89.802956
 dtype: float64,
 Ticker
 KO    84.158075
 dtype: float64,
 Ticker
 KO    98.012623
 dtype: float64,
 Ticker
 KO    94.302816
 dtype: float64,
 Ticker
 KO    82.908311
 dtype: float64,
 Ticker
 KO    78.472997
 dtype: float64,
 Ticker
 KO    83.623616
 dtype: float64,
 Ticker
 KO    101.056878
 dtype: float64,
 Ticker
 KO    93.723421
 dtype: float64,
 Ticker
 KO    72.087677
 dtype: float64,

### ¿Cual es el peor precio razonable para considerar?

In [200]:
resultados = np.array(resultados)

In [201]:
M = S_0 + S_0 * (Train.mean()) * 40
M

Ticker
KO    83.773306
dtype: float64

In [202]:
P_menor = np.percentile(resultados, 5)
P_menor

np.float64(75.59995486481222)

In [203]:
P_mayor = np.percentile(resultados, 95)
P_mayor

np.float64(106.25392660793521)

In [1]:
S0 = ...
mu = ...
sigma = ...
T = ...